:-use_module(library(clpfd)).

zebra(Zebra, Agua):-
    Nac = [Ing, Esp, Nor, Pt, Ucr],
    Beb = [Lar, Cha, Cafe, Leite, Agua],
    Animal = [Cao, Raposa, Iguana, Cavalo, Zebra],
    Cig = [Marlboro, Chesterfields, Luky, SGLights, Winston],
    Cor = [Amarelo, Azul, Verde, Branco, Vermelho],
    Sol = [Ing, Esp, Nor, Pt, Ucr, Lar, Cha, Cafe, Leite, Agua, Cao, Raposa, Iguana, Cavalo, Zebra, Marlboro, Chesterfields, Luky, SG Lights, Amarelo, Azul, Verde, Branco, Vermelho, Winston],
    all_different(Nac),
    all_different(Beb),
    all_different(Animal),
    all_different(Cig),
    all_different(Cor),
    Ing #= Vermelho,
    Esp #= Cao,
    Nor #= 1,
    Amarelo #= Marlboro,
    abs(Chesterfields - Raposa) #= 1,
    abs(Nor - Azul) #= 1,
    Winston #= Iguana,
    Luky #= Lar,
    Ucr #= Cha,
    Pt #= SGLights,
    abs(Marlboro - Cavalo) #= 1,
    Verde #= Cafe,
    Verde #= Branco + 1,
    Leite #= 3,
    labeling([], Sol).